[package]
name = "weir-macros"
version.workspace = true
edition.workspace = true

[dependencies]
weir-lexer.workspace = true
smol_str.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
weir-parser.workspace = true
weir-ast.workspace = true
