[package]
name = "weir-lexer"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
logos.workspace = true
smol_str.workspace = true

[dev-dependencies]
insta.workspace = true
