[package]
name = "weir-ast"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
la-arena.workspace = true
smol_str.workspace = true
weir-lexer.workspace = true

[dev-dependencies]
insta.workspace = true
