[package]
name = "weir-interp"
version.workspace = true
edition.workspace = true

[dependencies]
weir-ast.workspace = true
smol_str.workspace = true

[dev-dependencies]
weir-parser.workspace = true
insta.workspace = true
